### PR TITLE
feat(#352): SameXml from jeo 0.5.1

### LINKED ISSUE #352: The `SameXml` class is a duplicate from `jeo-maven-plugin`
`jeo-maven-plugin` have the same `SameXml` [class](https://github.com/objectionary/jeo-maven-plugin/blob/master/src/test/java/org/eolang/jeo/SameXml.java) in the repository. Recently I just copied this class to `opeo-maven-plugin`. But it's better to reuse it from `jeo-maven-plugin` instead. This is possible because `opeo-maven-plugin` uses `jeo-maven-plugin` as a dependency.

### PR DESCRIPTION
**Pull request by h1alexbel**
In this pull I've replaced `org.eolang.opeo.SameXml` as duplicate of `org.eolang.jeo.matchers.SameXml` to its origin from 
`jeo` version `0.5.1`.

@volodya-lombrozo take a look, please

closes #352

---

## PR-Codex overview
The focus of this PR is to replace usages of `org.eolang.opeo.SameXml` with `org.eolang.jeo.matchers.SameXml` in multiple test files.

### Detailed summary
- Replaced `org.eolang.opeo.SameXml` imports with `org.eolang.jeo.matchers.SameXml` in test files.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Review by volodya-lombrozo — APPROVED** [review]
@h1alexbel Perfect. Thank you! Looks good to me.

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by 0crat** [comment]
@h1alexbel Thanks for the contribution! You've earned +13 points for this: +30 as a basis; -7 for too many hits-of-code (171 >= 100); -10 for too few (2) comments. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+78](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Comment by 0crat** [comment]
@volodya-lombrozo Thanks for the review! You've earned +32 points for this: +25 as a basis; +17 for the 171 hits-of-code that you reviewed; -10 for too few (3) comments.  Your running balance is [+237](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Pull request merged**
