### PR TITLE
feat(#411): Fix The Problem With Opcode Names Spelling"

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
In this PR I added one more fix that solves the problem with opcode names that were written using uppercase.

Related to: #411.

---

## PR-Codex overview
This PR focuses on refactoring storage classes for XMIRs to handle lowercase opcodes and remove unnecessary aliases. 

### Detailed summary
- Removed `FormattingDecompiler` and `WithoutAliases` usage
- Added `LowerOpcodesStorage` and `WithoutAliasesStorage`
- Updated `SelectiveDecompiler` and `NaiveDecompiler` to use new storage classes

> The following files were skipped due to too many changes: `src/main/java/org/eolang/opeo/storage/LowerOpcodesStorage.java`, `src/test/java/org/eolang/opeo/storage/LowerOpcodesStorageTest.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you take a look, please? It is related to the #411 issue

**Review by yegor256 — APPROVED** [review]
@volodya-lombrozo LGTM

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by 0crat** [comment]
@yegor256 Hey there, great job on the review! 👏 You've scored **7** points for this one: +8 as a base, +9 for reviewing a whopping 478 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html), but -10 because we only saw 3 comments (we're aiming for at least 6). Remember, more comments could bump up your score next time! Your running balance is now [+261](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the awesome work!

**Comment by 0crat** [comment]
@volodya-lombrozo Hey there! 👋 Great job on your contribution! You've snagged +4 points for this one. Here's the breakdown: +16 base points, -8 for hitting that 200+ [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) mark (you're at 478!), and -4 for only having 3 comments. Remember, more comments can boost your score next time! [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) those contributions rolling in - you're doing awesome with a running balance of [+278](https://www.eolang.org/zerocracy/objectionary-vitals.html). Let's aim for even more points on your next submission! 💪

**Pull request merged**
