### PR TITLE
feat(#376): Towards Agent Base Acrhitecture

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
In this PR I has made an attempt to change an acritecture from "Handlers" to "Agents".
Agents are independent and try do decompile only those instructions, they understand.
This changes might make the architecture a bit less coupled.

Closes: #376.
History:
- **feat(#376): rename Add node to Addition**
- **feat(#376) handlers -> agents**
- **feat(#376): add several useful functions**
- **feat(#376): try to modify all agents to be independent**
- **feat(#376): fix some small mistakes**
- **feat(#376): each agent decides when to move to the next position**
- **feat(#376): fix all unit tests**
- **feat(#376): add a few puzzles**
- **feat(#376): fix several code offences**
- **feat(#376): fix all qulice suggestions**
- **feat(#376): change jacoco limits**

---

## PR-Codex overview
This PR adds a new `DecompilationAgent` interface and updates various classes to implement it. It also changes the package name and imports for consistency.

### Detailed summary
- Added `DecompilationAgent` interface
- Renamed and updated classes to implement `DecompilationAgent`
- Changed package name from `handlers` to `agents`
- Updated imports for consistency

> The following files were skipped due to too many changes: `src/main/java/org/eolang/opeo/ast/Opcode.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/BipushHandler.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/NewHandler.java`, `src/main/java/org/eolang/opeo/SelectiveDecompiler.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/LabelHandler.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/DupHandler.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/GetStaticHnadler.java`, `src/test/java/org/eolang/opeo/decompilation/DecompilerMachineTest.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/AddHandler.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/CheckCastHandler.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/SubstractionHandler.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/NewArrayHandler.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/IfHandler.java`, `src/main/java/org/eolang/opeo/decompilation/DecompilerMachine.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/PutFieldHnadler.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/MulHandler.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/InvokedynamicHandler.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/InvokestaticHander.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/InvokevirtualHandler.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/InvokeinterfaceHandler.java`, `src/main/java/org/eolang/opeo/decompilation/agents/PutFieldAgent.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/ReturnHandler.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/StoreToArrayHandler.java`, `src/main/java/org/eolang/opeo/decompilation/agents/LoadAgent.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/ConstHandler.java`, `src/main/java/org/eolang/opeo/decompilation/agents/CastAgent.java`, `src/test/java/org/eolang/opeo/ast/AddTest.java`, `src/main/java/org/eolang/opeo/decompilation/agents/StoreAgent.java`, `src/main/java/org/eolang/opeo/decompilation/DecompilerState.java`, `src/main/java/org/eolang/opeo/decompilation/handlers/InvokespecialHandler.java`, `src/main/java/org/eolang/opeo/decompilation/agents/AllAgents.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you take a look, please? There are lot's of changes, but they are rather similar.

**Comment by volodya-lombrozo** [comment]
@yegor256 friendly reminder

**Comment by yegor256** [comment]
@volodya-lombrozo looks good! However, it's rather hard to understand what exactly happens when those agents meet certain instructions. If you can create a set of tests (maybe in YAML files), where I can see something like this:

```yaml
opcodes:
  - ILOAD 423
  - ILOAD 7
  - IADD
agents:
  - AdditionAgent
  - SomeOtherAgent
eo:
  432.add 7
```

**Comment by volodya-lombrozo** [comment]
@yegor256 Agree. Added a [new issue](https://github.com/objectionary/opeo-maven-plugin/issues/381) for that tests. If all the rest is fine, could you **accept** this changes through a PR review, please? It seems, right now you leave only comments.

**Review by yegor256 — APPROVED** [review]
@volodya-lombrozo looks good, but integration tests are very much needed

**Comment by volodya-lombrozo** [comment]
@yegor256 Thank you for the review! I will try to implement this tests as soon as possible.

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by 0crat** [comment]
@volodya-lombrozo Thanks for your contribution! You've earned +5 points: +20 base, +30 for hits-of-code (capped at 30 for 2155 HOC), -7 for exceeding 200 HOC, -15 for exceeding 800 HOC, -15 for no code review, -10 for no reviewer comments. While the large code size impacted your score, we appreciate your effort. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming, but consider smaller, more focused changes. Your running balance is [+196](https://www.eolang.org/zerocracy/objectionary-vitals.html).

**Comment by 0crat** [comment]
@yegor256 🎉 Fantastic review! You've earned a whopping **+53 points**: +15 base, +30 for reviewing 2155 hits-of-code, and +8 for your 8 insightful comments. Your dedication is paying off - your balance now stands at [+145](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the great work! 💪

**Pull request merged**
