### PR TITLE
feat(#23): Add Docs to README - How to Use

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Add section 'How to Use' the plugin.
I also added the first integration test, to check that plugin works as explained in the README decription.

Closes: #23.
____
History:
- feat(#23): add the first draft of How to use section
- feat(#23): add How to Contribute section
- feat(#23): add CompileMojo for consistency
- feat(#23): add first integration test
- feat(#23): add checks for the integration test
- feat(#23): make several fixes to meet quality standarts

---

## PR-Codex overview
This PR focuses on renaming the `OpeoMojo` class to `DecompileMojo` and updating related test classes and documentation.

### Detailed summary
- Renamed `OpeoMojo` class to `DecompileMojo`
- Updated `OpeoMojoTest` to `DecompileMojoTest`
- Updated references to `OpeoMojo` in documentation

> The following files were skipped due to too many changes: `README.md`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you take a look, please?

**Review by yegor256 — APPROVED** [review]
looks good!

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.0.2`, title is `0.0.2`.

**Pull request merged**
