### PR TITLE
feat(#39): add site for opeo-maven-plugin

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Add site for `opeo-maven-plugin`:
- Add templates for generating html pages.
- GitHub pipeline to deploy the site.

Closes: #39.
____
History:
- feat(#39): add site yaml pipeline to deploy site generated by maven
- feat(#39): add doxia templates
- feat(#39): add site.xml
- feat(#39): format doxia templates

---

### Detailed summary
- Added a new page `404.apt.vm` with content for a Page Not Found error.
- Updated the `README.md` file with a link to the Maven site.
- Updated the `pom.xml` file with a new URL and description.
- Added a new page `index.apt.vm` with content for the OPEO Maven Plugin.
- Added a new workflow file `site.yaml` for building and deploying the site.
- Added a new `site.xml` file with project information and menu structure.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 reminder

**Review by yegor256 — APPROVED** [review]
looks good

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@rultor release, tag is `0.0.3`, title is `0.0.3`.

**Pull request merged**
