### PR TITLE
feat(#381): Add Agents Integration Test Examples

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
In this PR I added `AgentsIT` - the integration test that checks how different aggents work with the instruction set and how they change the decompilation output.

Closes: #381.

---

## PR-Codex overview
The focus of this PR is to enhance the decompilation process by adding a `TracedAgent` that logs agents used during decompilation. 

### Detailed summary
- Added `TracedAgent` to log agents used during decompilation
- Updated `DecompilerMachine` to accept `TracedAgent` output
- Updated `AllAgents` to include `TracedAgent` with output
- Added methods to `TracedAgent` to register and retrieve agents used
- Added tests to verify agents' decompilation behavior

> The following files were skipped due to too many changes: `src/test/java/it/AgentsIT.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you review that changes, please?

**Comment by volodya-lombrozo** [comment]
@yegor256 friendly reminder

**Review by yegor256 — APPROVED** [review]
@volodya-lombrozo perfect!

**Comment by volodya-lombrozo** [comment]
@rultor merge

**Comment by 0crat** [comment]
@yegor256 Hi there! Thanks for your code review. Based on our team's policy, you've earned +18 points for this contribution: +8 as a base reward, +6.64 for the 332 hits-of-code reviewed (capped at +16), and -10 for having fewer than 6 comments (only 2 were made). Remember, more detailed feedback helps improve code quality. Your updated balance is now [+251](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the good work, and don't hesitate to provide more comprehensive comments in future reviews! 👍

**Comment by 0crat** [comment]
@volodya-lombrozo 🎉 Great contribution! You've earned +4 points: +16 base, -8 for exceeding hits-of-code limit (332 ≥ 200), -4 for minimal comments (4). Your balance is now [+232](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the excellent work and [remember](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) to balance speed and quality. Looking forward to more!

**Comment by volodya-lombrozo** [comment]
@yegor256 It seems that the points awarded for reviews by 0crat are overpriced, or the points for contributions are underpriced.

**Pull request merged**
